FROM docker.elastic.co/elasticsearch/elasticsearch:7.8.0

RUN mkdir -p /app
WORKDIR /app
COPY . /app

RUN yum install -y gcc
RUN yum install -y gcc-c++

#RedHat Enterprise Server 7
RUN curl https://packages.microsoft.com/config/rhel/7/prod.repo > /etc/yum.repos.d/mssql-release.repo
RUN yum remove unixODBC-utf16 unixODBC-utf16-devel #to avoid conflicts
RUN ACCEPT_EULA=Y yum -y install msodbcsql17
# optional: for bcp and sqlcmd
RUN ACCEPT_EULA=Y yum -y install mssql-tools
RUN echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bash_profile
RUN echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
RUN source ~/.bashrc
# optional: for unixODBC development headers
RUN yum -y install unixODBC-devel

RUN yum update -y
RUN yum install -y python3-devel

RUN pip3 install -U pip
RUN pip3 install -r requirements.txt

HEALTHCHECK CMD curl -fsSL "http://$(hostname --ip-address):9200/_cat/health?h=status" | grep -E '^green'

ENTRYPOINT [ "python3" ]
CMD [ "indexer.py" ]
